SignTalk/SignTalk/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('videochat.urls')),
    path('user/', include('user.urls'))
]

SignTalk/user/urls.py
from django.urls import path
from . import views


app_name = 'user'
urlpatterns = [
    # path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
]

SignTalk/videochat/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index, name='index'),
    path('patient', views.patient, name='patient'),
    path('doctor',views.doctor, name='doctor')
]

SignTalk/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Doctor(AbstractUser):
    pass
    
    class Meta:
        verbose_name_plural = "Doctors"
    def __str__(self):
        return self.username



class Sessions(models.Model):
    Doctor = models.ForeignKey(Doctor, on_delete= models.CASCADE,related_name='sessions')
    meetingid = models.TextField(blank=False,null=False)
    patient = models.TextField(blank=False,null=False)
    date_added = models.DateTimeField(auto_now_add=True)
    
    
class MeetingIDs(models.Model):
    Doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="meetingID")
    meetingid = models.TextField(blank=False,null=False)
    data_added = models.DateField(auto_now_add=True)

SignTalk/videochat/models.py
from django.db import models

# Create your models here.

SignTalk/user/views.py
from django.shortcuts import render
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import JsonResponse
from django.shortcuts import HttpResponse, HttpResponseRedirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import Doctor
# Create your views here.


def index(request):
    
    # Authenticated users view their inbox
    if request.user.is_authenticated:
        return render(request, "videochat/room.html")

    # Everyone else is prompted to sign in
    else:
        return HttpResponseRedirect(reverse("login"))
    
    
    
    
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, username=email, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("doctor"))
        else:
            return render(request, "user/login.html", {
                "message": "Invalid email and/or password."
            })
    else:
        return render(request, "user/login.html")



def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        email = request.POST["email"]
        firstname = request.POST['Firstname']
        lastname = request.POST['Lastname']

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "user/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = Doctor.objects.create_user(email, email, password, first_name=firstname, last_name= lastname)
            user.save()
        except IntegrityError as e:
            print(e)
            return render(request, "user/register.html", {
                "message": "Email address already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "user/register.html")

SignTalk/videochat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
# Create your views here.


def index(request):
    if request.user.is_authenticated:
        logout(request)
    return render(request, 'videochat/index.html')
    # return render(request, 'videochat/room.html')
def patient(request):
    return render(request,'videochat/room.html')
@login_required
def doctor(request):
    return render(request,'videochat/room1.html')

SignTalk/user/templates/user/layout.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}My Chat{% endblock %}</title>
        {%bootstrap_css%}
        {%bootstrap_javascript jquery='full'%}
        {% block script %}
        {% endblock %}
        
    </head>
    <body>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

SignTalk/user/templates/user/layout2.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}My Chat{% endblock %}</title>
        {%bootstrap_css%}
        {%bootstrap_javascript jquery='full'%}
        {% block script %}
        {% endblock %}

        

    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href={% static "images/icons/favicon.ico" %}/>
<!--===============================================================================================-->
	{% comment %} <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css"> {% endcomment %}
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href= {% static "vendor/animate/animate.css" %}>
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href={% static "vendor/css-hamburgers/hamburgers.min.css" %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "vendor/select2/select2.min.css" %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static "usercss/util.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "usercss/main.css" %}>






    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %} " rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %} " rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %} " rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %} " rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/main.css' %} " rel="stylesheet">

    </head>
<body>
    <header id="header" class="header d-flex align-items-center">

        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
          <a href="{% url 'index' %}" class="logo d-flex align-items-center">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <!-- <img src="assets/img/logo.png" alt=""> -->
            <h1  style="color:white;">SignTalk<span>.</span></h1>
          </a>
          <nav id="navbar" class="navbar">
            <ul>
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'index' %}#about">About</a></li>
              <li><a href="{% url 'index' %}#services">Services</a></li>
              <!-- <li><a href="#portfolio">Portfolio</a></li> -->
              <!-- <li><a href="#team">Team</a></li> -->
              <!-- <li><a href="#">Doctor</a></li>
              <li><a href="#">Patient</a></li> -->
               <!-- <li><a href="#blog">Blog</a></li> -->
              <!-- <li class="dropdown"><a href="#"><span>Visit As</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a> -->
            <!-- <ul> -->
                  <!-- <li><a href="#">Drop Down 1</a></li>
                  <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a> 
                    <ul>
                      <li><a href="#">Deep Drop Down 1</a></li>
                      <li><a href="#">Deep Drop Down 2</a></li>
                      <li><a href="#">Deep Drop Down 3</a></li>
                      <li><a href="#">Deep Drop Down 4</a></li>
                      <li><a href="#">Deep Drop Down 5</a></li>
                    </ul>
                  </li> -->
                  <!-- <li><a href="#">Drop Down 2</a></li> -->
                   <!-- <li ><a href="#">Doctor</a></li> 
                  <li ><a href="#"> Patient</a></li>  -->
                <!-- </ul> -->
              </li>
              <!-- <li><a href="#contact">Contact</a></li>  -->
    
    
    
            </ul>
          </nav><!-- .navbar -->
    
          <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
          <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
    
        </div>
      </header><!-- End Header -->
      <!-- End Header -->
    
        {% block body %}
        {% endblock %}


    <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-info">
          <a href="index.html" class="logo d-flex align-items-center">
            <span>SignTalk.</span>
          </a>
          <p>
            SignTalk is a health care app that seeks to provide
            quality health care to all people especially the
            physicall impaired dumb or deaf person. It will serve to provide effective communication to ensure sense of belongingness.
          </p>
          <div class="social-links d-flex mt-4">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <!-- <h4>Useful Links</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Terms of service</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul> -->
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><a href="#hero">Home</a></li>           
            <li><a href="#about">About</a></li>
            <li><a href="#services">Service</a></li>
       
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contact Us</h4>
          <p>
             SignTalk Global Solutions,<br>
             Post Office Box AD432,<br>
             Adum - Ashanti, Ghana. <br><br>
            <strong>Phone:</strong> +233(0) 554 54 8855<br>
            <strong>Email:</strong> info@signtalkglobal.com<br>
          </p>

        </div>

      </div>
    </div>

    <div class="container mt-4">
      <div class="copyright">
        &copy; Copyright <strong><span>SignTalk</span></strong>. All Rights Reserved
      </div>
  
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->


</body>
</html>

SignTalk/user/templates/user/login.html
{% extends "user/layout2.html" %}
{% load static %}
{% block body %}

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img width="55%" class="m-auto d-block" src={% static 'images/login1.png' %} alt="IMG">
            </div>

            <form class="login100-form validate-form" action="{% url 'user:login' %}" method="post">
                {% csrf_token %}
                {% if message %}
                        <div class="alert alert-danger alert-dismissable" role="alert">
                            {{ message }}
                            <button class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times; </span></button>
                        </div>
                        
                {% endif %}
                <span class="login100-form-title">
                    Doctor Login
                </span>

                <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                    <input class="input100" type="text" name="email" placeholder="Email">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input" data-validate = "Password is required">
                    <input class="input100" type="password" name="password" placeholder="Password">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>
                
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        Login
                    </button>
                </div>

                <div class="text-center p-t-12">
                    <span class="txt1">
                        Forgot
                    </span>
                    <a class="txt2" href="#">
                        Username / Password?
                    </a>
                </div>

                <div class="text-center p-t-30">
                    <a class="txt2" href={% url 'user:register' %}>
                        Create your Account
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>




<!--===============================================================================================-->	
<script src={% static "vendor/jquery/jquery-3.2.1.min.js" %}></script>
<!--===============================================================================================-->
<script src={% static "vendor/bootstrap/js/popper.js" %}></script>
<script src={% static "vendor/bootstrap/js/bootstrap.min.js" %}></script>
<!--===============================================================================================-->
<script src= {% static  "vendor/select2/select2.min.js" %}></script>
<!--===============================================================================================-->
<script src={% static "vendor/tilt/tilt.jquery.min.js" %}></script>
<script >
    $('.js-tilt').tilt({
        scale: 1.1
    })
</script>
<!--===============================================================================================-->
<script src={% static "userjs/main.js" %}></script>


{% endblock %}















    {% comment %} <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="email" name="email" placeholder="Email">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a> {% endcomment %}

SignTalk/user/templates/user/register.html
{% extends "user/layout2.html" %}
{% load static %}
{% block body %}

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="p-4">

                <div class="login100-pic js-tilt" data-tilt>
                    <img width="55%" class="m-auto d-block"  src={% static 'images/doctor.png' %} alt="IMG">
                </div>
                <div class="p-t-50 text-center">
                    Are you a doctor? You have to sign up first
                </div>
            </div>
            
            <form class="login100-form validate-form" action="{% url 'user:register' %}" method="post">
                {% csrf_token %}
                {% if message %}
                        <div class="alert alert-danger alert-dismissable" role="alert">
                            {{ message }}
                            <button class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times; </span></button>
                        </div>
                        
                {% endif %}
                <span class="login100-form-title">
                    Doctor Signup
                </span>

                <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                    <input class="input100" type="text" name="email" placeholder="Email">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input" data-validate = "Firstname is required">
                    <input class="input100" type="text" name="Firstname" placeholder="Firstname">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-id-card" aria-hidden="true"></i>
                    </span>
                </div>
                <div class="wrap-input100 validate-input" data-validate = "Lastname is required">
                    <input class="input100" type="text" name="Lastname" placeholder="Lastname">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-id-card" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input" data-validate = "Password is required">
                    <input class="input100" type="password" name="password" placeholder="Password">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>
                <div class="wrap-input100 validate-input" data-validate = "Confirmation Password is required">
                    <input class="input100" type="password" name="confirmation" placeholder="Confirm Password">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>
                
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        Signup
                    </button>
                </div>

                <div class="text-center p-t-12">
                    <span class="txt1">
                        Forgot
                    </span>
                    <a class="txt2" href="#">
                        Username / Password?
                    </a>
                </div>

                <div class="text-center p-t-30">
                    <a class="txt2" href={% url 'user:login' %}>
                        Login into your account
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>




<!--===============================================================================================-->	
<script src={% static "vendor/jquery/jquery-3.2.1.min.js" %}></script>
<!--===============================================================================================-->
<script src={% static "vendor/bootstrap/js/popper.js" %}></script>
<script src={% static "vendor/bootstrap/js/bootstrap.min.js" %}></script>
<!--===============================================================================================-->
<script src= {% static  "vendor/select2/select2.min.js" %}></script>
<!--===============================================================================================-->
<script src={% static "vendor/tilt/tilt.jquery.min.js" %}></script>
<script >
    $('.js-tilt').tilt({
        scale: 1.1
    })
</script>
<!--===============================================================================================-->
<script src={% static "userjs/main.js" %}></script>

















    {% comment %} <h2>Register</h2>
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}


    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a> {% endcomment %}

{% endblock %}

SignTalk/videochat/templates/videochat/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Django Channels</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/main.css' %}" rel="stylesheet">
    </head>
    <body>
        <h3 id="label-username">
            Username
        </h3>

        <div>
            <input type="text" id="username" >
            <button id="btn-join">Join Room</button>
        </div>
        

        <div class="main-grid-container">
            <div id="video-container">
                <div>
                    <video id="local-video" style="float: left" autoplay playsinline></video>
                </div>
                <button id="btn-toggle-audio">Audio Mute</button>
                <button id="btn-toggle-video">Video Off</button>
            </div>
            <div id="server-video">
                <canvas id="canvas" width="400" height="300"></canvas>
                <img id="server-frame" width="400" height="300">
            </div>
            <div id="chat">
                <h3>CHAT</h3>
                <div id="messages">
                    <ul id="message-list"></ul>
                </div>
                <div>
                    <input type="text" id="msg">
                    <button id="btn-send-msg"> Send Message</button>
                </div>
                <button id="btn-share-screen">Share Screen</button>
            </div>
        </div>

        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    </body>
</html>